"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "fr"
type Direction = "ltr"

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    dir: Direction
    toggleLanguage: () => void
}

const translations = {
    en: {
        "common.currency": "MAD",
        // Navigation
        "nav.shop": "Shop",
        "nav.collections": "Collections",
        "nav.about": "About",
        "nav.faq": "FAQ",
        "nav.search": "Search",
        "nav.shop_now": "Shop Now",
        "nav.view_all_collections": "View All Collections",

        // Header Popups
        "header.categories": "Categories",
        "header.browse_by_category": "Browse by Category",
        "header.face_care": "Computers & Laptops",
        "header.face_care_desc": "High performance workstations",
        "header.hair_care": "Servers & Storage",
        "header.hair_care_desc": "Enterprise grade solutions",
        "header.body_care": "Printers & Scanners",
        "header.body_care_desc": "Professional printing",
        "header.gift_sets": "Components",
        "header.gift_sets_desc": "Processors, RAM & more",
        "header.new_arrival": "New Arrival",
        "header.argan_elixir": "Gaming Rigs",
        "header.argan_elixir_desc": "Ultimate performance for gamers",
        "header.signature": "Enterprise",
        "header.essentials": "Home Office",
        "header.premium": "Gaming",

        // Hero
        "hero.title_prefix": "Didali",
        "hero.title_suffix": "Store",
        "hero.subtitle": "Leader in IT distribution in Morocco. Wholesale provider of PCs, servers, printers, and more.",
        "hero.shop_collection": "Browse Products",
        "hero.explore_best_sellers": "View Best Sellers",
        "hero.fast_delivery": "Fast Delivery",
        "hero.secure_checkout": "Secure Payment",
        "hero.easy_returns": "Official Warranty",
        "hero.pure_argan_oil": "Genuine Products",
        "hero.cold_pressed": "Best Prices",

        // Sections
        "section.featured_collections": "Featured Departments",
        "section.featured_desc": "Browse our wide range of IT equipment",
        "section.best_sellers": "Categories",
        "section.best_sellers_desc": "Show all our categories here",
        "section.all_categories": "All",
        "section.view_all_products": "View All Products",
        "section.load_more": "Load More",
        "section.why_choose": "Why Choose Didali Store?",
        "section.organic": "100% Genuine",
        "section.organic_desc": "Authentic products from top brands",
        "section.award_winning": "Industry Leader",
        "section.award_winning_desc": "More than 20 years of experience",
        "section.cruelty_free": "Full Warranty",
        "section.cruelty_free_desc": "Official manufacturer warranty",
        "section.handcrafted": "Expert Support",
        "section.handcrafted_desc": "Technical guidance from IT professionals",
        "section.limited_offer": "Limited Time Offer",
        "section.promo_title": "25% Off Your First Order",
        "section.promo_desc": "Get the best deal on your first order. Use code WELCOME25 at checkout.",
        "section.get_offer": "Get the Offer",
        "section.hurry_up": "Hurry Up!",
        "section.view_collection": "View Collection",

        // Newsletter
        "newsletter.title": "Stay in the Loop",
        "newsletter.desc": "Subscribe for exclusive offers, skincare tips, and new product launches.",
        "newsletter.placeholder": "Enter your email",
        "newsletter.subscribe": "Subscribe",
        "newsletter.disclaimer": "By subscribing, you agree to our Privacy Policy. Unsubscribe anytime.",

        // Footer
        "footer.company": "Company",
        "footer.support": "Support",
        "footer.legal": "Legal",
        "footer.our_story": "Our Story",
        "footer.sustainability": "Sustainability",
        "footer.press": "Press",
        "footer.careers": "Careers",
        "footer.contact_us": "Contact Us",
        "footer.shipping_info": "Shipping Info",
        "footer.track_order": "Track Order",
        "footer.privacy_policy": "Privacy Policy",
        "footer.terms": "Terms of Service",
        "footer.refund_policy": "Refund Policy",
        "footer.cookies": "Cookies",
        "footer.rights": "All rights reserved.",

        // Product & Cart
        "product.add_to_cart": "Add to Cart",
        "product.reviews": "reviews",
        "product.in_stock": "In Stock",
        "product.low_stock": "Low Stock",
        "product.out_of_stock": "Out of Stock",
        "product.select_size": "Select Size",
        "product.quantity": "Quantity",
        "product.features": "Key Features",
        "product.specifications": "Technical Specifications",
        "product.warranty": "Warranty & Support",
        "product.you_may_also_like": "You May Also Like",
        "cart.your_cart_empty": "Your Cart is Empty",
        "cart.empty_desc": "Looks like you haven't added any items to your cart yet.",
        "cart.start_shopping": "Start Shopping",
        "cart.shopping_cart": "Shopping Cart",
        "cart.items": "items",
        "cart.order_summary": "Order Summary",
        "cart.subtotal": "Subtotal",
        "cart.shipping": "Shipping",
        "cart.free": "Free",
        "cart.total": "Total",
        "cart.proceed_checkout": "Proceed to Checkout",
        "cart.promo_code": "Promo Code",
        "cart.apply": "Apply",
        "cart.applied": "Applied",
        "cart.enter_code": "Enter code",
        "cart.discount_applied": "discount applied!",
        "cart.add_more_shipping": "Add more for free shipping",
        "cart.continue_shopping": "Continue Shopping",
        "cart.trust.shipping": "Free Shipping MAD 750+",
        "cart.trust.secure": "Secure Payment",
        "cart.trust.returns": "30-Day Returns",

        // Order statuses (for labels/badges)
        "order.status.pending": "Pending",
        "order.status.processing": "Processing",
        "order.status.shipped": "Shipped",
        "order.status.delivered": "Delivered",
        "order.status.cancelled": "Cancelled",

        // FAQ
        "faq.title": "Frequently Asked Questions",
        "faq.subtitle": "Everything you need to know about our products",
        "faq.q1": "What kind of products do you sell?",
        "faq.a1": "We are a wholesale distributor of IT equipment including PCs, laptops, servers, printers, and networking gear from top brands.",
        "faq.q2": "Do you offer warranty?",
        "faq.a2": "Yes, all our products come with official manufacturer warranty.",
        "faq.q3": "Do you sell to individuals?",
        "faq.a3": "We primarily serve businesses and resellers, but we also sell to individuals.",
        "faq.q4": "Where are you located?",
        "faq.a4": "We are based in Morocco and serve customers nationwide.",
        "faq.q5": "How can I get a quote?",
        "faq.a5": "You can request a quote through our website or contact our sales team directly.",
        "faq.q6": "Do you provide technical support?",
        "faq.a6": "Yes, our team of experts can assist you with technical inquiries and solution design.",

        // Checkout
        "checkout.title": "Checkout",
        "checkout.contact_info": "Contact Information",
        "checkout.full_name": "Full Name",
        "checkout.phone": "Phone Number",
        "checkout.email": "Email (Optional)",
        "checkout.city": "City",
        "checkout.address": "Address",
        "checkout.pay": "Pay",
        "checkout.processing": "Processing...",
        "checkout.success_title": "Order Confirmed!",
        "checkout.success_desc": "We have received your order. We will call you shortly to confirm the details.",
        "checkout.continue_shopping": "Continue Shopping",
        "checkout.cancel_title": "Payment Cancelled",
        "checkout.cancel_desc": "Your payment was cancelled. No charges were made.",
        "checkout.return_cart": "Return to Cart",
        "checkout.retry": "Retry Payment",
        "validation.required": "This field is required",
        "validation.phone": "Please enter a valid phone number (min 10 chars)",
        "validation.email": "Please enter a valid email address",

        // Success Page
        "success.thank_you": "Thank You",
        "success.order_confirmed": "Your order is confirmed",
        "success.coupon_title": "A special gift for you",
        "success.coupon_desc": "Use this code for 20% off your next purchase",
        "success.order_summary": "Order Summary",
        "footer.about_desc": "Didali Store - Your trusted partner for IT hardware and solutions in Morocco. Empowering businesses with technology.",
        "footer.privacy_short": "Privacy",
        "footer.terms_short": "Terms",
        "footer.system_status": "System Normal",

        // WhatsApp
        "whatsapp.title": "Stay in the Loop on WhatsApp",
        "whatsapp.desc": "Join our VIP list for exclusive discounts, skincare tips, and early access to new launches directly to your phone.",
        "whatsapp.placeholder": "Phone number",
        "whatsapp.button": "Join Now",
        "whatsapp.success_title": "You're on the list!",
        "whatsapp.success_desc": "Thank you for subscribing. We've sent a welcome gift to your WhatsApp.",
        "whatsapp.disclaimer": "By joining, you agree to receive marketing messages on WhatsApp. Opt-out anytime.",
        "whatsapp.register_another": "Register Another Number",
        "whatsapp.verified_updates": "Verified WhatsApp Updates",
        "whatsapp.processing": "Processing...",

        // Timer
        "timer.days": "Days",
        "timer.hours": "Hours",
        "timer.minutes": "Minutes",
        "timer.seconds": "Seconds",
        "timer.loading": "Loading Products...",

        // Accessibility
        "accessibility.go_to_slide": "Go to slide",

        // Dashboard - Admin
        "dashboard.admin.title": "Dashboard",
        "dashboard.admin.overview": "Detailed overview",
        "dashboard.admin.search_placeholder": "Search orders, customers, products... (Ctrl+K)",
        "dashboard.admin.export": "Export",
        "dashboard.admin.import": "Import",

        // Admin Orders
        "admin.orders.title": "Orders",
        "admin.orders.subtitle": "Manage and track orders",
        "admin.orders.export": "Export",
        "admin.orders.create_order": "Create Order",
        "admin.orders.search_placeholder": "Search orders...",
        "admin.orders.status.all": "All",
        "admin.orders.status.processing": "Processing",
        "admin.orders.status.delivered": "Delivered",
        "admin.orders.status.pending": "Pending",
        "admin.orders.status.cancelled": "Cancelled",
        "admin.orders.table.order": "Order",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Customer",
        "admin.orders.table.items": "Items",
        "admin.orders.table.total": "Total",
        "admin.orders.table.status": "Status",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Loading orders...",
        "admin.orders.no_orders": "No orders found",
        "admin.orders.no_orders_match": "No orders found matching your criteria",
        "admin.orders.showing": "Showing {current} of {total} orders",
        "admin.orders.view_details": "View Details",

        // Admin Order details (extra labels)
        "admin.orders.update_status": "Update Status",
        "admin.orders.timeline_title": "Timeline Logs",
        "admin.orders.timeline_empty": "No logs available.",
        "admin.orders.customer_title": "Customer",
        "admin.orders.customer_company": "Company",
        "admin.orders.customer_contact": "Contact",
        "admin.orders.customer_email": "Email",

        // Admin Products
        "admin.products.title": "Products",
        "admin.products.subtitle": "Manage your inventory",
        "admin.products.import_csv": "Import CSV",
        "admin.products.manage_categories": "Manage Categories",
        "admin.products.add_product": "Add Product",
        "admin.products.category_name_en": "Category Name (English)",
        "admin.products.category_name_ar": "Category Name (Arabic)",
        "admin.products.add": "Add",
        "admin.products.search_categories": "Search categories...",
        "admin.products.delete_category_confirm": "Delete this category? Products using it will need to be recategorized.",
        "admin.products.stats.total_products": "Total Products",
        "admin.products.stats.total_inventory": "Total Inventory",
        "admin.products.stats.low_stock": "Low Stock",
        "admin.products.stats.out_of_stock": "Out of Stock",
        "admin.products.search_placeholder": "Search products...",
        "admin.products.table.product": "Product",
        "admin.products.table.category": "Category",
        "admin.products.table.price": "Price",
        "admin.products.table.stock": "Stock",
        "admin.products.table.status": "Status",
        "admin.products.table.actions": "Actions",
        "admin.products.no_products": "No products found matching your criteria.",
        "admin.products.delete_product_confirm": "Are you sure you want to delete this product?",
        "admin.products.qty": "Qty",
        "admin.products.units": "units",
        "admin.products.uploading": "Uploading...",

        // Admin Sidebar
        "admin.sidebar.dashboard": "Dashboard",
        "admin.sidebar.orders": "Orders",
        "admin.sidebar.products": "Products",
        "admin.sidebar.customers": "Customers",
        "admin.sidebar.resellers": "Resellers",
        "admin.sidebar.account_managers": "Account Managers",
        "admin.sidebar.shipping": "Shipping",
        "admin.sidebar.analytics": "Analytics",
        "admin.sidebar.hero_carousel": "Hero Carousel",
        "admin.sidebar.whatsapp_leads": "WhatsApp Leads",
        "admin.sidebar.contact_messages": "Contact Messages",
        "admin.sidebar.career_applications": "Career Applications",
        "admin.sidebar.settings": "Settings",
        "admin.sidebar.logout": "Logout",

        // Admin Hero
        "admin.hero.title": "Hero Carousel",
        "admin.hero.subtitle": "Customize your homepage slider. High-quality images (16:9 or 4:3) work best. Link slides to products to drive sales. Important: Make sure to set slides to \"Active\" for them to appear in the store.",
        "admin.hero.add_slide": "Add Slide",
        "admin.hero.refresh": "Refresh",
        "admin.hero.change_image": "Change Image",
        "admin.hero.title_label": "Title",
        "admin.hero.subtitle_label": "Subtitle",
        "admin.hero.placeholder_title": "Slide Title",
        "admin.hero.placeholder_subtitle": "Small text above title",
        "admin.hero.linked_product": "Linked Product",
        "admin.hero.no_link": "No Link (Just Image)",
        "admin.hero.select_product": "Select Product",
        "admin.hero.active": "Active",
        "admin.hero.inactive": "Inactive",
        "admin.hero.save": "Save",
        "admin.hero.saved": "Saved",
        "admin.hero.delete": "Delete",
        "admin.hero.max_size": "Max 5MB images",
        "admin.hero.recommended_size": "Recommended: 1920x1080px or 1200x1200px",
        "admin.hero.slides_configured": "{count} Slides configured",
        "admin.hero.toast.upload_image": "Please upload an image file",
        "admin.hero.toast.image_large": "Image size must be less than 5MB",
        "admin.hero.toast.uploading": "Uploading image...",
        "admin.hero.toast.upload_success": "Image uploaded successfully",
        "admin.hero.toast.upload_fail": "Failed to update image",
        "admin.hero.toast.adding": "Adding new slide...",
        "admin.hero.toast.add_success": "Slide added! Now upload an image.",
        "admin.hero.toast.add_fail": "Failed to add slide",
        "admin.hero.toast.delete_confirm": "Are you sure you want to delete this slide?",
        "admin.hero.toast.deleting": "Deleting slide...",
        "admin.hero.toast.delete_success": "Slide deleted",
        "admin.hero.toast.delete_fail": "Failed to delete slide",
        "admin.hero.toast.no_image_fail": "Cannot activate a slide without an image",
        "admin.hero.toast.activating": "Activating...",
        "admin.hero.toast.deactivating": "Deactivating...",
        "admin.hero.toast.status_success_on": "Slide activated",
        "admin.hero.toast.status_success_off": "Slide deactivated",
        "admin.hero.toast.status_fail": "Failed to update status",
        "admin.hero.toast.save_success": "Saved successfully",
        "admin.hero.toast.save_fail": "Failed to save",

        // Admin Contacts
        "admin.contacts.back": "Back to dashboard",
        "admin.contacts.title": "Contact messages",
        "admin.contacts.list_title": "Messages from clients, partners & distributors",
        "admin.contacts.subtitle": "Click the \"View\" button to read full message content in a dialog.",
        "admin.contacts.table.name": "Name",
        "admin.contacts.table.email": "Email",
        "admin.contacts.table.phone": "Phone",
        "admin.contacts.table.type": "Type",
        "admin.contacts.table.message": "Message",
        "admin.contacts.table.date": "Date",
        "admin.contacts.no_messages": "No messages yet. Connect the Contact Us form to a database to see messages here.",
        "admin.contacts.view": "View",
        "admin.contacts.details_title": "Message details",
        "admin.contacts.label.name": "Name:",
        "admin.contacts.label.email": "Email:",
        "admin.contacts.label.phone": "Phone:",
        "admin.contacts.label.company": "Company:",
        "admin.contacts.label.type": "Type:",

        // Admin Careers
        "admin.careers.back": "Back to dashboard",
        "admin.careers.title": "Career applications",
        "admin.careers.list_title": "Applications to join the team",
        "admin.careers.subtitle": "Click the \"View\" button on each row to read the full application summary in a dialog.",
        "admin.careers.table.name": "Name",
        "admin.careers.table.email": "Email",
        "admin.careers.table.phone": "Phone",
        "admin.careers.table.role": "Role",
        "admin.careers.table.cv": "CV file",
        "admin.careers.table.summary": "Summary",
        "admin.careers.table.date": "Date",
        "admin.careers.no_applications": "No applications yet. Connect the Careers form to a database to see applications here.",
        "admin.careers.open_cv": "Open CV",
        "admin.careers.no_file": "No file",
        "admin.careers.view": "View",
        "admin.careers.details_title": "Application details",
        "admin.careers.label.name": "Name:",
        "admin.careers.label.email": "Email:",
        "admin.careers.label.phone": "Phone:",
        "admin.careers.label.role": "Role:",
        "admin.careers.label.cv": "CV file:",

        // Admin Order details (extra labels)
        "admin.orders.update_status": "Update Status",
        "admin.orders.timeline_title": "Timeline Logs",
        "admin.orders.timeline_empty": "No logs available.",
        "admin.orders.customer_title": "Customer",
        "admin.orders.customer_company": "Company",
        "admin.orders.customer_contact": "Contact",
        "admin.orders.customer_email": "Email",

        // Admin Settings
        "admin.settings.title": "Admin Configuration",
        "admin.settings.subtitle": "Global settings for Didali Store",
        "admin.settings.reset": "Reset",
        "admin.settings.update": "Update Systems",
        "admin.settings.toast.success": "Settings updated successfully",
        "admin.settings.toast.error": "Failed to update settings",
        "admin.settings.toast.push_sent": "Sent to {count} device(s)",
        "admin.settings.toast.push_no_sub": "No active subscriptions found for this store.",
        "admin.settings.toast.push_fail": "Failed to trigger test notification",
        "admin.settings.tabs.general": "General",
        "admin.settings.tabs.marketing": "Marketing",
        "admin.settings.tabs.payments": "Payments",
        "admin.settings.tabs.alerts": "Alerts",
        "admin.settings.tabs.security": "Security",
        "admin.settings.tabs.team": "Team",
        "admin.settings.general.action_required": "Action Required",
        "admin.settings.general.caught_up": "All caught up! No urgent alerts.",
        "admin.settings.general.reminders_title": "Internal Reminders",
        "admin.settings.general.reminders_desc": "Use internal notes on reseller profiles to track performance reviews and follow-up requirements. These are shared with Admins but hidden from resellers.",
        "admin.settings.general.identity_title": "Identity & Localization",
        "admin.settings.general.label.store_name": "Store Name",
        "admin.settings.general.label.support_email": "Support Email",
        "admin.settings.general.label.currency": "Main Currency",
        "admin.settings.general.channels_title": "Contact Channels",
        "admin.settings.general.label.whatsapp": "WhatsApp Business Number",
        "admin.settings.general.label.phone": "Direct Support Line",
        "admin.settings.marketing.title": "Global Announcements & Promotions",
        "admin.settings.marketing.label.en_content": "English Content",
        "admin.settings.marketing.label.ar_content": "Arabic Content",
        "admin.settings.marketing.label.announcement": "Header Announcement",
        "admin.settings.marketing.label.hero_title": "Hero Section Title",
        "admin.settings.marketing.label.hero_subtitle": "Hero Subtitle",
        "admin.settings.marketing.label.promo_code": "Active Promo Code",
        "admin.settings.marketing.promo_desc": "Applied at checkout and displayed in some store sections.",
        "admin.settings.payments.gateways_title": "Standard Gateways",
        "admin.settings.payments.cod_title": "Cash on Delivery (COD)",
        "admin.settings.payments.cod_desc": "Standard Morocco payment",
        "admin.settings.payments.cheque_title": "Cheque Payment",
        "admin.settings.payments.cheque_desc": "For corporate & enterprise",
        "admin.settings.payments.label.payee_info": "Payee Info",
        "admin.settings.payments.wire_title": "Bank Wire Transfers",
        "admin.settings.payments.transfer_title": "Transfer (Virement)",
        "admin.settings.payments.transfer_desc": "IBAN / RIB based payment",
        "admin.settings.payments.label.banking_details": "Banking Details",
        "admin.settings.alerts.title": "Push Notifications",
        "admin.settings.alerts.desc": "Real-time system alerts for orders and inventory status directly to your mobile or desktop.",
        "admin.settings.alerts.global_toggle": "Global Push Service",
        "admin.settings.alerts.global_desc": "Master toggle for the store notification engine.",
        "admin.settings.alerts.register_device": "Register Current Device",
        "admin.settings.alerts.send_ping": "Send System Ping",
        "admin.settings.alerts.guide_title": "Setup Guide",
        "admin.settings.alerts.guide_ios_title": "iOS / iPhone",
        "admin.settings.alerts.guide_ios_desc": "1. Open this page in Safari\n2. Tap Share → \"Add to Home Screen\"\n3. Open from home screen and Subscribe.",
        "admin.settings.alerts.guide_android_title": "Android / Desktop",
        "admin.settings.alerts.guide_android_desc": "Browser must be open or background tasks enabled. Works natively on Chrome/Edge.",
        "admin.settings.security.title": "Dashboard Protection",
        "admin.settings.security.desc": "The Admin PIN protects sensitive operations and dashboard entry.",
        "admin.settings.security.label.pin": "System Access PIN",
        "admin.settings.security.warning": "Warning: Changing the PIN will take immediate effect across all administrative entry points.",
        "admin.settings.team.title": "Account Manager Dashboard",
        "admin.settings.team.label.fallback": "Default Status Message",
        "admin.settings.team.fallback_desc": "Displayed in the 'Action Required' widget when there are no pending orders.",
        "admin.settings.team.label.guidance": "Internal Guidance",
        "admin.settings.team.guidance_desc": "Displayed in the 'Internal Reminders' widget on the manager dashboard.",

        // Admin WhatsApp
        "admin.whatsapp.back": "Back to dashboard",
        "admin.whatsapp.title": "WhatsApp Leads",
        "admin.whatsapp.list_title": "WhatsApp subscription list",
        "admin.whatsapp.subtitle": "This page is a placeholder to display numbers from the \"Stay in the Loop on WhatsApp\" form.",
        "admin.whatsapp.table.country": "Country code",
        "admin.whatsapp.table.phone": "Phone",
        "admin.whatsapp.table.date": "Subscribed at",
        "admin.whatsapp.no_data": "No data yet. Connect the WhatsApp form to a database to see numbers here.",

        // Admin Shipping
        "admin.shipping.title": "Shipping Rules",
        "admin.shipping.subtitle": "Control shipping costs and free delivery thresholds for different types of customers.",
        "admin.shipping.refresh": "Refresh",
        "admin.shipping.save_rules": "Save Rules",
        "admin.shipping.customer_rules": "{role} Customer Rules",
        "admin.shipping.reseller_rules": "Reseller Customer Rules",
        "admin.shipping.partner_rules": "Partner Customer Rules",
        "admin.shipping.wholesaler_rules": "Wholesaler Customer Rules",
        "admin.shipping.configure_costs": "Configure costs and thresholds",
        "admin.shipping.status": "Status",
        "admin.shipping.base_cost": "Base Shipping Cost",
        "admin.shipping.fixed_fee_desc": "Fixed fee added to orders below threshold.",
        "admin.shipping.free_threshold_amount": "Free Shipping (Amount)",
        "admin.shipping.amount_required_desc": "Amount required for free delivery.",
        "admin.shipping.free_threshold_items": "Free Shipping (Items)",
        "admin.shipping.min_items_desc": "Minimum items required for free delivery.",
        "admin.shipping.order_logic": "Order logic:",
        "admin.shipping.rule_logic_desc": "Orders will cost {price} {currency} unless they exceed {threshold} {currency} or contain at least {items} items.",
        "admin.shipping.rule_disabled": "Shipping rule is currently disabled.",
        "admin.shipping.no_rules": "No shipping rules found. Please check database configuration.",
        "admin.shipping.retry": "Retry Loading",
        "admin.shipping.success_update": "Shipping settings updated successfully",
        "admin.shipping.error_update": "Failed to update settings",

        // Admin Analytics / Dashboard Stats
        "admin.analytics.title": "Analytics",
        "admin.analytics.subtitle": "Deep dive into performance",
        "admin.analytics.loading": "Gathering intelligence...",
        "admin.analytics.total_revenue": "Total Revenue",
        "admin.analytics.conversion_rate": "Conversion Rate",
        "admin.analytics.active_sessions": "Active Sessions",
        "admin.analytics.avg_order_value": "Avg. Order Value",
        "admin.analytics.revenue_over_time": "Revenue Over Time",
        "admin.dashboard.stats.total_revenue": "Total Revenue",
        "admin.dashboard.stats.total_orders": "Total Orders",
        "admin.dashboard.stats.total_resellers": "Total Resellers",
        "admin.dashboard.stats.total_customers": "Guest Customers",
        "admin.dashboard.stats.partners_label": "Partners",
        "admin.dashboard.stats.direct_label": "Direct",
        "admin.dashboard.recent_orders.title": "Recent Orders",
        "admin.dashboard.recent_orders.view_all": "View All",
        "admin.dashboard.recent_orders.loading": "Loading...",
        "admin.dashboard.recent_orders.empty": "No recent orders found.",
        "admin.dashboard.recent_orders.col_order_id": "Order ID",
        "admin.dashboard.recent_orders.col_customer": "Customer",
        "admin.dashboard.recent_orders.col_email": "Email",
        "admin.dashboard.recent_orders.col_amount": "Amount",
        "admin.dashboard.recent_orders.col_status": "Status",
        "admin.dashboard.recent_orders.col_action": "Action",
        "admin.analytics.top_products": "Top Products",
        "admin.analytics.sales_count": "{count} sales",
        "admin.analytics.no_sales_data": "No sales data yet",
        "admin.analytics.channel_performance": "Channel Performance",
        "admin.analytics.visitor_locality": "Visitor Locality",
        "admin.analytics.visitor_locality_desc": "Implement session tracking to see real-time visitor geographic data.",

        // Account Managers Page
        "account_managers.title": "Account Managers",
        "account_managers.subtitle": "Manage corporate accounts and reseller assignments",
        "account_managers.add_manager": "Add Manager",
        "account_managers.create_title": "Create Account Manager",
        "account_managers.create_desc": "Fill in the details to create a new dedicated manager account.",
        "account_managers.full_name": "Full Name",
        "account_managers.work_email": "Work Email",
        "account_managers.password": "Password",
        "account_managers.phone": "Phone Number",
        "account_managers.create_account": "Create Manager Account",
        "account_managers.created_success": "Account Manager created successfully!",
        "account_managers.no_managers": "No Account Managers Found",
        "account_managers.no_managers_desc": "Start by adding your first manager to handle reseller relations.",
        "account_managers.assigned_accounts": "Assigned Accounts",
        "account_managers.prime_goal": "Prime Goal",
        "account_managers.edit_goal": "Edit Goal",
        "account_managers.goal_updated": "Prime Goal updated successfully",
        "account_managers.assign_resellers": "Assign Resellers",
        "account_managers.search_resellers": "Search resellers...",
        "account_managers.search_managers": "Search managers by name or email...",
        "account_managers.no_resellers_available": "No resellers available for assignment",
        "account_managers.assignment_updated": "Assignment updated!",
        "account_managers.reseller_unassigned": "Reseller unassigned!",
        "account_managers.delete_confirm": "Are you sure you want to delete {name}? This will permanently remove their account and unassign all their resellers.",
        "account_managers.deleted_success": "Account Manager deleted",
        "account_managers.unassign": "Unassign",
        "account_managers.assign": "Assign",
        "account_managers.delete_account": "Delete Account",
        "account_managers.manage_assignments": "Manage Assignments",
        "account_managers.select_resellers": "Select which resellers this manager should be responsible for.",
        "account_managers.find_reseller": "Find reseller by company or contact name...",
        "account_managers.no_match_search": "No available resellers match your search.",
        "account_managers.all_assigned": "All resellers are already assigned to other account managers.",
        "account_managers.reassign": "Reassign",
        "account_managers.set_prime_goal": "Set Prime Goal",
        "account_managers.set_goal_desc": "Set the revenue target for",
        "account_managers.target_revenue": "Target Revenue (MAD)",
        "account_managers.default_revenue": "Default is 200,000 MAD.",
        "account_managers.update": "Update",
        "account_managers.save": "Save",
        "account_managers.cancel": "Cancel",
        "account_managers.manager": "Manager",
        "account_managers.active": "Active",
        "account_managers.company": "Company",
        "account_managers.contact": "Contact",
        "account_managers.email": "Email",
        "account_managers.phone_label": "Phone",
        "account_managers.city": "City",
        "account_managers.loading": "Loading account managers...",
        "account_managers.error_loading": "Failed to load account managers",
        "account_managers.assigned_partners": "Assigned Partners",
        "common.unknown": "Unknown",

        // Reseller Dashboard
        "reseller.dashboard.title": "Reseller Dashboard",
        "reseller.dashboard.welcome_back": "Welcome back, {name}",
        "reseller.dashboard.browse_catalog": "Browse Catalog",
        "reseller.dashboard.total_orders": "Total Orders",
        "reseller.dashboard.total_value": "Total Value",
        "reseller.dashboard.organization_profile": "Organization Profile",
        "reseller.dashboard.company_name": "Company Name",
        "reseller.dashboard.not_set": "Not set",
        "reseller.dashboard.business_identification": "Business Identification (ICE)",
        "reseller.dashboard.location": "Location",
        "reseller.dashboard.site": "Site",
        "reseller.dashboard.view": "View",
        "reseller.dashboard.dedicated_account_manager": "Dedicated Account Manager",
        "reseller.dashboard.no_account_manager": "No account manager assigned yet",
        "reseller.dashboard.transaction_history": "Transaction History",
        "reseller.dashboard.order": "Order",
        "reseller.dashboard.orders": "Orders",
        "reseller.dashboard.no_transactions": "No Transactions Recorded",
        "reseller.dashboard.initialize_trade": "Initialize Trade",
        "reseller.dashboard.initialize_desc": "Initialize your wholesale journey today and unlock Tier-1 inventory pricing.",
        "reseller.dashboard.start_now": "Start Now",
        "reseller.dashboard.reference_id": "Reference ID",
        "reseller.dashboard.timestamp": "Timestamp",
        "reseller.dashboard.fulfillment": "Fulfillment",
        "reseller.dashboard.volume": "Volume",
        "reseller.dashboard.action": "Action",
        "reseller.dashboard.view_order": "View",
        "reseller.dashboard.total": "Total",
        "reseller.dashboard.signed_out": "Signed out successfully",

        // Manager Dashboard
        "manager.dashboard.title": "Dashboard",
        "manager.dashboard.overview": "Overview of your assigned accounts",
        "manager.dashboard.assigned_clients": "Assigned Clients",
        "manager.dashboard.clients_desc": "Resellers, Partners & Wholesalers",
        "manager.dashboard.total_orders": "Total Orders",
        "manager.dashboard.total_orders_desc": "All time orders",
        "manager.dashboard.total_revenue": "Total Revenue",
        "manager.dashboard.total_revenue_desc": "From all orders",
        "manager.dashboard.pending_orders": "Pending Orders",
        "manager.dashboard.pending_orders_desc": "Require attention",
        "manager.dashboard.recent_orders": "Recent Orders",
        "manager.dashboard.recent_orders_desc": "Latest orders from your clients",
        "manager.dashboard.view_all": "View All",
        "manager.dashboard.no_orders": "No orders yet",
        "manager.dashboard.assigned_clients_title": "Assigned Clients",
        "manager.dashboard.your_reseller_accounts": "Your reseller accounts",
        "manager.dashboard.no_clients": "No clients assigned yet",

        // Manager Orders
        "manager.orders.title": "Orders",
        "manager.orders.subtitle": "All orders from your assigned clients",
        "manager.orders.search_placeholder": "Search orders...",
        "manager.orders.filter_all": "All",
        "manager.orders.filter_pending": "Pending",
        "manager.orders.filter_processing": "Processing",
        "manager.orders.filter_delivered": "Delivered",
        "manager.orders.filter_cancelled": "Cancelled",
        "manager.orders.order_number": "Order #",
        "manager.orders.customer": "Customer",
        "manager.orders.date": "Date",
        "manager.orders.status": "Status",
        "manager.orders.total": "Total",
        "manager.orders.view": "View",
        "manager.orders.no_orders": "No orders found",
        "manager.orders.loading": "Loading orders...",

        // Manager Resellers
        "manager.resellers.title": "Clients",
        "manager.resellers.subtitle": "Your assigned resellers, partners and wholesalers",
        "manager.resellers.search_placeholder": "Search clients...",
        "manager.resellers.revenue_goal": "Revenue Goal",
        "manager.resellers.current_revenue": "Current Revenue",
        "manager.resellers.target": "Target",
        "manager.resellers.progress": "Progress",
        "manager.resellers.company": "Company",
        "manager.resellers.contact": "Contact",
        "manager.resellers.email": "Email",
        "manager.resellers.phone": "Phone",
        "manager.resellers.city": "City",
        "manager.resellers.total_orders": "Total Orders",
        "manager.resellers.total_revenue": "Total Revenue",
        "manager.resellers.view_profile": "View Profile",
        "manager.resellers.no_resellers": "No clients found",
        "manager.resellers.loading": "Loading clients...",

        // Admin Resellers Page
        "admin.resellers.title": "Reseller Performance",
        "admin.resellers.subtitle": "Monitoring {count} active wholesale distribution partners",
        "admin.resellers.total_resellers": "Total Resellers",
        "admin.resellers.total_partners": "Total Partners",
        "admin.resellers.total_wholesalers": "Total Wholesalers",
        "admin.resellers.partner_network": "Partner Network",
        "admin.resellers.total_spend": "Total Spend",
        "admin.resellers.all_partners": "All Partners",
        "admin.resellers.top_spend": "Top Spend",
        "admin.resellers.search_placeholder": "Filter partners by name or company...",
        "admin.resellers.loading": "Initializing Partner Data...",
        "admin.resellers.reseller_identity": "Reseller Identity",
        "admin.resellers.company_ice": "Company / ICE",
        "admin.resellers.performance": "Performance",
        "admin.resellers.location": "Location",
        "admin.resellers.account_manager": "Account Manager",
        "admin.resellers.nexus_profile": "Nexus Profile",
        "admin.resellers.personal_account": "Personal Account",
        "admin.resellers.ice": "ICE",
        "admin.resellers.na": "N/A",
        "admin.resellers.unknown": "Unknown",
        "admin.resellers.unassigned": "Unassigned",
        "admin.resellers.view_profile": "View Profile",
        "admin.resellers.no_resellers": "Zero Partners Detected",
        "admin.resellers.no_resellers_description": "Try adjusting your spectral filters to find matching distribution entities.",
        "admin.resellers.reseller": "Reseller",
        "admin.resellers.partner": "Partner",
        "admin.resellers.wholesaler": "Wholesaler",
        "admin.resellers.error_loading": "Failed to load resellers",
        // Admin Dashboard Stats
        "admin.dashboard.stats.total_revenue": "Revenu Total",
        "admin.dashboard.stats.total_orders": "Commandes Totales",
        "admin.dashboard.stats.total_resellers": "Revendeurs",
        "admin.dashboard.stats.total_customers": "Clients Invités",
        "admin.dashboard.stats.partners_label": "Partenaires",
        "admin.dashboard.stats.direct_label": "Direct",
        "admin.dashboard.recent_orders.title": "Commandes récentes",
        "admin.dashboard.recent_orders.view_all": "Voir tout",
        "admin.dashboard.recent_orders.loading": "Chargement...",
        "admin.dashboard.recent_orders.empty": "Aucune commande récente trouvée.",
        "admin.dashboard.recent_orders.col_order_id": "ID Commande",
        "admin.dashboard.recent_orders.col_customer": "Client",
        "admin.dashboard.recent_orders.col_email": "Email",
        "admin.dashboard.recent_orders.col_amount": "Montant",
        "admin.dashboard.recent_orders.col_status": "Statut",
        "admin.dashboard.recent_orders.col_action": "Action",
    },
    fr: {
        "common.currency": "MAD",
        // Navigation
        "nav.shop": "Boutique",
        "nav.collections": "Collections",
        "nav.about": "À propos",
        "nav.faq": "FAQ",
        "nav.search": "Rechercher",
        "nav.shop_now": "Acheter",
        "nav.view_all_collections": "Voir toutes les collections",

        // Header Popups
        "header.categories": "Catégories",
        "header.browse_by_category": "Parcourir par catégorie",
        "header.face_care": "Ordinateurs & Portables",
        "header.face_care_desc": "Stations de travail haute performance",
        "header.hair_care": "Serveurs & Stockage",
        "header.hair_care_desc": "Solutions pour entreprises",
        "header.body_care": "Imprimantes & Scanners",
        "header.body_care_desc": "Impression professionnelle",
        "header.gift_sets": "Composants",
        "header.gift_sets_desc": "Processeurs, RAM & plus",
        "header.new_arrival": "Nouveautés",
        "header.argan_elixir": "Gaming",
        "header.argan_elixir_desc": "Performance ultime pour gamers",
        "header.signature": "Entreprise",
        "header.essentials": "Bureau",
        "header.premium": "Gaming",

        // Hero
        "hero.title_prefix": "Didali",
        "hero.title_suffix": "Store",
        "hero.subtitle": "Leader de la distribution informatique au Maroc. Grossiste en PC, serveurs, imprimantes et plus.",
        "hero.shop_collection": "Parcourir les produits",
        "hero.explore_best_sellers": "Voir les meilleures ventes",
        "hero.fast_delivery": "Livraison Rapide",
        "hero.secure_checkout": "Paiement Sécurisé",
        "hero.easy_returns": "Garantie Officielle",
        "hero.pure_argan_oil": "Produits Authentiques",
        "hero.cold_pressed": "Meilleurs Prix",

        // Sections
        "section.featured_collections": "Départements Vedettes",
        "section.featured_desc": "Découvrez notre large gamme d'équipements informatiques",
        "section.best_sellers": "Catégories",
        "section.best_sellers_desc": "Afficher toutes nos catégories ici",
        "section.all_categories": "Tout",
        "section.view_all_products": "Voir tous les produits",
        "section.load_more": "Charger plus",
        "section.why_choose": "Pourquoi choisir Didali Store ?",
        "section.organic": "100% Authentique",
        "section.organic_desc": "Produits authentiques des grandes marques",
        "section.award_winning": "Leader du marché",
        "section.award_winning_desc": "Plus de 20 ans d'expérience",
        "section.cruelty_free": "Garantie Complète",
        "section.cruelty_free_desc": "Garantie constructeur officielle",
        "section.handcrafted": "Support Expert",
        "section.handcrafted_desc": "Conseils techniques par des pros",
        "section.limited_offer": "Offre Limitée",
        "section.promo_title": "25% de remise sur votre 1ère commande",
        "section.promo_desc": "Profitez de la meilleure offre pour votre première commande. Utilisez le code WELCOME25.",
        "section.get_offer": "Profiter de l'offre",
        "section.hurry_up": "Dépêchez-vous !",
        "section.view_collection": "Voir la collection",

        // Newsletter
        "newsletter.title": "Restez informé",
        "newsletter.desc": "Abonnez-vous pour des offres exclusives et les nouveaux lancements de produits.",
        "newsletter.placeholder": "Entrez votre email",
        "newsletter.subscribe": "S'abonner",
        "newsletter.disclaimer": "En vous abonnant, vous acceptez notre politique de confidentialité. Désinscription à tout moment.",

        // WhatsApp
        "whatsapp.title": "Restez connecté sur WhatsApp",
        "whatsapp.desc": "Rejoignez notre liste VIP pour des remises exclusives et un accès prioritaire aux nouveautés.",
        "whatsapp.placeholder": "Numéro de téléphone",
        "whatsapp.button": "Rejoindre maintenant",
        "whatsapp.success_title": "Vous êtes sur la liste !",
        "whatsapp.success_desc": "Merci de votre inscription. Un cadeau de bienvenue vous a été envoyé.",
        "whatsapp.disclaimer": "En rejoignant, vous acceptez de recevoir des messages marketing sur WhatsApp.",
        "whatsapp.register_another": "Inscrire un autre numéro",
        "whatsapp.verified_updates": "Mises à jour vérifiées",
        "whatsapp.processing": "Traitement...",

        // Footer
        "footer.company": "Entreprise",
        "footer.support": "Support",
        "footer.legal": "Légal",
        "footer.our_story": "Notre histoire",
        "footer.sustainability": "Durabilité",
        "footer.press": "Presse",
        "footer.careers": "Carrières",
        "footer.contact_us": "Contactez-nous",
        "footer.shipping_info": "Livraison",
        "footer.track_order": "Suivre ma commande",
        "footer.privacy_policy": "Politique de confidentialité",
        "footer.terms": "Conditions d'utilisation",
        "footer.refund_policy": "Politique de remboursement",
        "footer.cookies": "Cookies",
        "footer.rights": "Tous droits réservés.",
        "footer.about_desc": "Didali Store - Votre partenaire de confiance pour le matériel et les solutions informatiques au Maroc.",
        "footer.privacy_short": "Confidentialité",
        "footer.terms_short": "Conditions",
        "footer.system_status": "Système Opérationnel",

        // Product & Cart
        "product.add_to_cart": "Ajouter au panier",
        "product.reviews": "avis",
        "product.in_stock": "En Stock",
        "product.low_stock": "Stock Faible",
        "product.out_of_stock": "Rupture de stock",
        "product.select_size": "Choisir la taille",
        "product.quantity": "Quantité",
        "product.features": "Caractéristiques Clés",
        "product.specifications": "Spécifications Techniques",
        "product.warranty": "Garantie & Support",
        "product.you_may_also_like": "Vous aimerez aussi",
        "cart.your_cart_empty": "Votre panier est vide",
        "cart.empty_desc": "Il semblerait que vous n'ayez rien ajouté à votre panier pour le moment.",
        "cart.start_shopping": "Commencer vos achats",
        "cart.shopping_cart": "Panier",
        "cart.items": "articles",
        "cart.order_summary": "Résumé de la commande",
        "cart.subtotal": "Sous-total",
        "cart.shipping": "Livraison",
        "cart.free": "Gratuit",
        "cart.total": "Total",
        "cart.proceed_checkout": "Passer à la caisse",
        "cart.promo_code": "Code Promo",
        "cart.apply": "Appliquer",
        "cart.applied": "Appliqué",
        "cart.enter_code": "Entrer le code",
        "cart.discount_applied": "Remise appliquée !",
        "cart.add_more_shipping": "Ajoutez plus pour la livraison gratuite",
        "cart.continue_shopping": "Continuer vos achats",
        "cart.trust.shipping": "Livraison Gratuite > 750 MAD",
        "cart.trust.secure": "Paiement Sécurisé",
        "cart.trust.returns": "Retours sous 30 jours",

        // Order statuses (for labels/badges)
        "order.status.pending": "En attente",
        "order.status.processing": "En traitement",
        "order.status.shipped": "Expédiée",
        "order.status.delivered": "Livrée",
        "order.status.cancelled": "Annulée",

        // FAQ
        "faq.title": "Questions Fréquentes",
        "faq.subtitle": "Tout ce que vous devez savoir sur nos produits",
        "faq.q1": "Quels types de produits vendez-vous ?",
        "faq.a1": "Nous sommes un distributeur grossiste d'équipements informatiques, incluant PC, serveurs, imprimantes et réseaux.",
        "faq.q2": "Offrez-vous une garantie ?",
        "faq.a2": "Oui, tous nos produits sont couverts par la garantie officielle du fabricant.",
        "faq.q3": "Vendez-vous aux particuliers ?",
        "faq.a3": "Nous servons principalement les entreprises et revendeurs, mais vendons aussi aux particuliers.",
        "faq.q4": "Où êtes-vous situés ?",
        "faq.a4": "Nous sommes basés au Maroc et servons des clients dans tout le royaume.",
        "faq.q5": "Comment obtenir un devis ?",
        "faq.a5": "Vous pouvez demander un devis via notre site web ou contacter notre équipe commerciale.",
        "faq.q6": "Fournissez-vous un support technique ?",
        "faq.a6": "Oui, notre équipe d'experts peut vous assister pour vos questions techniques et la conception de solutions.",

        // Checkout
        "checkout.title": "Paiement",
        "checkout.contact_info": "Informations de contact",
        "checkout.full_name": "Nom complet",
        "checkout.phone": "Numéro de téléphone",
        "checkout.email": "Email (Optionnel)",
        "checkout.city": "Ville",
        "checkout.address": "Adresse",
        "checkout.pay": "Payer",
        "checkout.processing": "Traitement...",
        "checkout.success_title": "Commande Confirmée !",
        "checkout.continue_shopping": "Continuer vos achats",
        "checkout.cancel_title": "Paiement Annulé",
        "checkout.cancel_desc": "Votre paiement a été annulé. Aucun débit n'a été effectué.",
        "checkout.return_cart": "Retour au panier",
        "checkout.retry": "Réessayer",
        "validation.required": "Ce champ est requis",
        "validation.phone": "Veuillez entrer un numéro valide (min 10 car.)",
        "validation.email": "Veuillez entrer un email valide",

        // Success Page
        "success.thank_you": "Merci",
        "success.order_confirmed": "Votre commande est confirmée",
        "checkout.success_desc": "Nous avons bien reçu votre commande. Nous vous appellerons bientôt pour confirmer.",
        "success.coupon_title": "Un cadeau pour vous",
        "success.coupon_desc": "Utilisez ce code pour 20% de réduction sur votre prochain achat",
        "success.order_summary": "Résumé de la commande",

        // Timer
        "timer.days": "Jours",
        "timer.hours": "Heures",
        "timer.minutes": "Min",
        "timer.seconds": "Sec",
        "timer.loading": "Chargement...",

        // Accessibility
        "accessibility.go_to_slide": "Aller à la diapositive",

        // Dashboard - Admin
        "dashboard.admin.title": "Tableau de Bord",
        "dashboard.admin.overview": "Aperçu détaillé",
        "dashboard.admin.search_placeholder": "Rechercher des commandes, clients, produits... (Ctrl+K)",
        "dashboard.admin.export": "Exporter",
        "dashboard.admin.import": "Importer",

        // Admin Orders
        "admin.orders.title": "Commandes",
        "admin.orders.subtitle": "Gérer et suivre les commandes",
        "admin.orders.export": "Exporter",
        "admin.orders.create_order": "Créer une commande",
        "admin.orders.search_placeholder": "Rechercher des commandes...",
        "admin.orders.status.all": "Tout",
        "admin.orders.status.processing": "En traitement",
        "admin.orders.status.delivered": "Livrée",
        "admin.orders.status.pending": "En attente",
        "admin.orders.status.cancelled": "Annulée",
        "admin.orders.table.order": "Commande",
        "admin.orders.table.date": "Date",
        "admin.orders.table.customer": "Client",
        "admin.orders.table.items": "Articles",
        "admin.orders.table.total": "Total",
        "admin.orders.table.status": "Statut",
        "admin.orders.table.actions": "Actions",
        "admin.orders.loading": "Chargement des commandes...",
        "admin.orders.no_orders": "Aucune commande trouvée",
        "admin.orders.no_orders_match": "Aucune commande ne correspond à vos critères",
        "admin.orders.showing": "Affichage de {current} sur {total} commandes",
        "admin.orders.view_details": "Voir les détails",

        // Admin Products
        "admin.products.title": "Produits",
        "admin.products.subtitle": "Gérez votre inventaire",
        "admin.products.import_csv": "Importer CSV",
        "admin.products.manage_categories": "Gérer les catégories",
        "admin.products.add_product": "Ajouter un produit",
        "admin.products.category_name_en": "Nom de catégorie (Anglais)",
        "admin.products.category_name_ar": "Nom de catégorie (Arabe)",
        "admin.products.add": "Ajouter",
        "admin.products.search_categories": "Rechercher des catégories...",
        "admin.products.delete_category_confirm": "Supprimer cette catégorie ? Les produits l'utilisant devront être recatégorisés.",
        "admin.products.stats.total_products": "Total Produits",
        "admin.products.stats.total_inventory": "Inventaire Total",
        "admin.products.stats.low_stock": "Stock Faible",
        "admin.products.stats.out_of_stock": "Rupture de Stock",
        "admin.products.search_placeholder": "Rechercher des produits...",
        "admin.products.table.product": "Produit",
        "admin.products.table.category": "Catégorie",
        "admin.products.table.price": "Prix",
        "admin.products.table.stock": "Stock",
        "admin.products.table.status": "Statut",
        "admin.products.table.actions": "Actions",
        "admin.products.no_products": "Aucun produit trouvé correspondant à vos critères.",
        "admin.products.delete_product_confirm": "Êtes-vous sûr de vouloir supprimer ce produit ?",
        "admin.products.qty": "Qté",
        "admin.products.units": "unités",
        "admin.products.uploading": "Téléchargement...",

        // Admin Sidebar
        "admin.sidebar.dashboard": "Tableau de bord",
        "admin.sidebar.orders": "Commandes",
        "admin.sidebar.products": "Produits",
        "admin.sidebar.customers": "Clients",
        "admin.sidebar.resellers": "Revendeurs",
        "admin.sidebar.account_managers": "Gestionnaires de compte",
        "admin.sidebar.shipping": "Livraison",
        "admin.sidebar.analytics": "Analytique",
        "admin.sidebar.hero_carousel": "Carrousel Hero",
        "admin.sidebar.whatsapp_leads": "Leads WhatsApp",
        "admin.sidebar.contact_messages": "Messages de contact",
        "admin.sidebar.career_applications": "Candidatures",
        "admin.sidebar.settings": "Paramètres",
        "admin.sidebar.logout": "Déconnexion",

        // Admin Hero
        "admin.hero.title": "Carrousel Hero",
        "admin.hero.subtitle": "Personnalisez le curseur de votre page d'accueil. Les images de haute qualité (16:9 ou 4:3) fonctionnent le mieux. Liez les diapositives aux produits pour stimuler les ventes. Important : Assurez-vous d'activer les diapositives pour qu'elles apparaissent dans la boutique.",
        "admin.hero.add_slide": "Ajouter une Diapositive",
        "admin.hero.refresh": "Actualiser",
        "admin.hero.change_image": "Changer l'Image",
        "admin.hero.title_label": "Titre",
        "admin.hero.subtitle_label": "Sous-titre",
        "admin.hero.placeholder_title": "Titre de la Diapositive",
        "admin.hero.placeholder_subtitle": "Petit texte au-dessus du titre",
        "admin.hero.linked_product": "Produit Lié",
        "admin.hero.no_link": "Aucun Lien (Image uniquement)",
        "admin.hero.select_product": "Sélectionner un Produit",
        "admin.hero.active": "Actif",
        "admin.hero.inactive": "Inactif",
        "admin.hero.save": "Enregistrer",
        "admin.hero.saved": "Enregistré",
        "admin.hero.delete": "Supprimer",
        "admin.hero.max_size": "Images max 5 Mo",
        "admin.hero.recommended_size": "Recommandé : 1920x1080px ou 1200x1200px",
        "admin.hero.slides_configured": "{count} Diapositives configurées",
        "admin.hero.toast.upload_image": "Veuillez télécharger un fichier image",
        "admin.hero.toast.image_large": "La taille de l'image doit être inférieure à 5 Mo",
        "admin.hero.toast.uploading": "Téléchargement de l'image...",
        "admin.hero.toast.upload_success": "Image téléchargée avec succès",
        "admin.hero.toast.upload_fail": "Échec de la mise à jour de l'image",
        "admin.hero.toast.adding": "Ajout d'une nouvelle diapositive...",
        "admin.hero.toast.add_success": "Diapositive ajoutée ! Téléchargez une image maintenant.",
        "admin.hero.toast.add_fail": "Échec de l'ajout de la diapositive",
        "admin.hero.toast.delete_confirm": "Êtes-vous sûr de vouloir supprimer cette diapositive ?",
        "admin.hero.toast.deleting": "Suppression de la diapositive...",
        "admin.hero.toast.delete_success": "Diapositive supprimée",
        "admin.hero.toast.delete_fail": "Échec de la suppression de la diapositive",
        "admin.hero.toast.no_image_fail": "Impossible d'activer une diapositive sans image",
        "admin.hero.toast.activating": "Activation...",
        "admin.hero.toast.deactivating": "Désactivation...",
        "admin.hero.toast.status_success_on": "Diapositive activée",
        "admin.hero.toast.status_success_off": "Diapositive désactivée",
        "admin.hero.toast.status_fail": "Échec de la mise à jour du statut",
        "admin.hero.toast.save_success": "Enregistré avec succès",
        "admin.hero.toast.save_fail": "Échec de l'enregistrement",

        // Admin Contacts
        "admin.contacts.back": "Retour au tableau de bord",
        "admin.contacts.title": "Messages de contact",
        "admin.contacts.list_title": "Messages des clients, partenaires et distributeurs",
        "admin.contacts.subtitle": "Cliquez sur le bouton \"Afficher\" pour lire le contenu complet du message dans une boîte de dialogue.",
        "admin.contacts.table.name": "Nom",
        "admin.contacts.table.email": "E-mail",
        "admin.contacts.table.phone": "Téléphone",
        "admin.contacts.table.type": "Type",
        "admin.contacts.table.message": "Message",
        "admin.contacts.table.date": "Date",
        "admin.contacts.no_messages": "Aucun message pour le moment. Connectez le formulaire de contact à une base de données pour voir les messages ici.",
        "admin.contacts.view": "Afficher",
        "admin.contacts.details_title": "Détails du message",
        "admin.contacts.label.name": "Nom :",
        "admin.contacts.label.email": "E-mail :",
        "admin.contacts.label.phone": "Téléphone :",
        "admin.contacts.label.company": "Entreprise :",
        "admin.contacts.label.type": "Type :",

        // Admin Careers
        "admin.careers.back": "Retour au tableau de bord",
        "admin.careers.title": "Candidatures",
        "admin.careers.list_title": "Candidatures pour rejoindre l'équipe",
        "admin.careers.subtitle": "Cliquez sur le bouton \"Afficher\" sur chaque ligne pour lire le résumé complet de la candidature dans une boîte de dialogue.",
        "admin.careers.table.name": "Nom",
        "admin.careers.table.email": "E-mail",
        "admin.careers.table.phone": "Téléphone",
        "admin.careers.table.role": "Rôle",
        "admin.careers.table.cv": "Fichier CV",
        "admin.careers.table.summary": "Résumé",
        "admin.careers.table.date": "Date",
        "admin.careers.no_applications": "Aucune candidature pour le moment. Connectez le formulaire de carrière à une base de données pour voir les candidatures ici.",
        "admin.careers.open_cv": "Ouvrir le CV",
        "admin.careers.no_file": "Aucun fichier",
        "admin.careers.view": "Afficher",
        "admin.careers.details_title": "Détails de la candidature",
        "admin.careers.label.name": "Nom :",
        "admin.careers.label.email": "E-mail :",
        "admin.careers.label.phone": "Téléphone :",
        "admin.careers.label.role": "Rôle :",
        "admin.careers.label.cv": "Fichier CV :",

        // Admin Order details (extra labels)
        "admin.orders.update_status": "Mettre à jour le statut",
        "admin.orders.timeline_title": "Historique des statuts",
        "admin.orders.timeline_empty": "Aucun journal disponible.",
        "admin.orders.customer_title": "Client",
        "admin.orders.customer_company": "Entreprise",
        "admin.orders.customer_contact": "Contact",
        "admin.orders.customer_email": "E-mail",

        // Admin Settings
        "admin.settings.title": "Configuration de l'Administration",
        "admin.settings.subtitle": "Paramètres globaux pour Didali Store",
        "admin.settings.reset": "Réinitialiser",
        "admin.settings.update": "Mettre à jour les systèmes",
        "admin.settings.toast.success": "Paramètres mis à jour avec succès",
        "admin.settings.toast.error": "Échec de la mise à jour des paramètres",
        "admin.settings.toast.push_sent": "Envoyé à {count} appareil(s)",
        "admin.settings.toast.push_no_sub": "Aucun abonnement actif trouvé pour ce magasin.",
        "admin.settings.toast.push_fail": "Échec du déclenchement de la notification de test",
        "admin.settings.tabs.general": "Général",
        "admin.settings.tabs.marketing": "Marketing",
        "admin.settings.tabs.payments": "Paiements",
        "admin.settings.tabs.alerts": "Alertes",
        "admin.settings.tabs.security": "Sécurité",
        "admin.settings.tabs.team": "Équipe",
        "admin.settings.general.action_required": "Action Requise",
        "admin.settings.general.caught_up": "Tout est à jour ! Pas d'alertes urgentes.",
        "admin.settings.general.reminders_title": "Rappels Internes",
        "admin.settings.general.reminders_desc": "Utilisez les notes internes sur les profils des revendeurs pour suivre les évaluations de performance et les besoins de suivi. Celles-ci sont partagées avec les administrateurs mais cachées aux revendeurs.",
        "admin.settings.general.identity_title": "Identité et Localisation",
        "admin.settings.general.label.store_name": "Nom du magasin",
        "admin.settings.general.label.support_email": "E-mail d'assistance",
        "admin.settings.general.label.currency": "Devise principale",
        "admin.settings.general.channels_title": "Canaux de contact",
        "admin.settings.general.label.whatsapp": "Numéro WhatsApp Business",
        "admin.settings.general.label.phone": "Ligne d'assistance directe",
        "admin.settings.marketing.title": "Annonces et Promotions Globales",
        "admin.settings.marketing.label.en_content": "Contenu Anglais",
        "admin.settings.marketing.label.ar_content": "Contenu Arabe",
        "admin.settings.marketing.label.announcement": "Annonce d'en-tête",
        "admin.settings.marketing.label.hero_title": "Titre de la section Hero",
        "admin.settings.marketing.label.hero_subtitle": "Sous-titre Hero",
        "admin.settings.marketing.label.promo_code": "Code Promo Actif",
        "admin.settings.marketing.promo_desc": "Appliqué lors du paiement et affiché dans certaines sections du magasin.",
        "admin.settings.payments.gateways_title": "Passerelles Standards",
        "admin.settings.payments.cod_title": "Paiement à la livraison (COD)",
        "admin.settings.payments.cod_desc": "Paiement standard au Maroc",
        "admin.settings.payments.cheque_title": "Paiement par chèque",
        "admin.settings.payments.cheque_desc": "Pour les entreprises et les sociétés",
        "admin.settings.payments.label.payee_info": "Informations sur le bénéficiaire",
        "admin.settings.payments.wire_title": "Virements Bancaires",
        "admin.settings.payments.transfer_title": "Virement",
        "admin.settings.payments.transfer_desc": "Paiement basé sur IBAN / RIB",
        "admin.settings.payments.label.banking_details": "Coordonnées bancaires",
        "admin.settings.alerts.title": "Notifications Push",
        "admin.settings.alerts.desc": "Alertes système en temps réel pour les commandes et le statut des stocks directement sur votre mobile ou votre bureau.",
        "admin.settings.alerts.global_toggle": "Service Push Global",
        "admin.settings.alerts.global_desc": "Interrupteur principal pour le moteur de notifications du magasin.",
        "admin.settings.alerts.register_device": "Enregistrer l'appareil actuel",
        "admin.settings.alerts.send_ping": "Envoyer un ping système",
        "admin.settings.alerts.guide_title": "Guide de configuration",
        "admin.settings.alerts.guide_ios_title": "iOS / iPhone",
        "admin.settings.alerts.guide_ios_desc": "1. Ouvrez cette page dans Safari\n2. Appuyez sur Partager → \"Sur l'écran d'accueil\"\n3. Ouvrez depuis l'écran d'accueil et abonnez-vous.",
        "admin.settings.alerts.guide_android_title": "Android / Bureau",
        "admin.settings.alerts.guide_android_desc": "Le navigateur doit être ouvert ou les tâches en arrière-plan activées. Fonctionne nativement sur Chrome/Edge.",
        "admin.settings.security.title": "Protection du Tableau de Bord",
        "admin.settings.security.desc": "Le code PIN administrateur protège les opérations sensibles et l'entrée dans le tableau de bord.",
        "admin.settings.security.label.pin": "Code PIN d'accès au système",
        "admin.settings.security.warning": "Attention : La modification du code PIN prendra effet immédiatement sur tous les points d'entrée administratifs.",
        "admin.settings.team.title": "Tableau de Bord du Gestionnaire de Compte",
        "admin.settings.team.label.fallback": "Message de statut par défaut",
        "admin.settings.team.fallback_desc": "Affiché dans le widget 'Action Requise' lorsqu'il n'y a pas de commandes en attente.",
        "admin.settings.team.label.guidance": "Conseils Internes",
        "admin.settings.team.guidance_desc": "Affiché dans le widget 'Rappels Internes' sur le tableau de bord du gestionnaire.",

        // Admin WhatsApp
        "admin.whatsapp.back": "Retour au tableau de bord",
        "admin.whatsapp.title": "Leads WhatsApp",
        "admin.whatsapp.list_title": "Liste des abonnés WhatsApp",
        "admin.whatsapp.subtitle": "Cette page est un espace réservé pour afficher les numéros du formulaire.",
        "admin.whatsapp.table.country": "Code pays",
        "admin.whatsapp.table.phone": "Téléphone",
        "admin.whatsapp.table.date": "Abonné le",
        "admin.whatsapp.no_data": "Aucune donnée pour le moment.",

        // Admin Shipping
        "admin.shipping.title": "Règles de Livraison",
        "admin.shipping.subtitle": "Contrôlez les frais de livraison et les seuils de livraison gratuite pour différents types de clients.",
        "admin.shipping.refresh": "Actualiser",
        "admin.shipping.save_rules": "Enregistrer les Règles",
        "admin.shipping.customer_rules": "Règles Client {role}",
        "admin.shipping.reseller_rules": "Règles Revendeur",
        "admin.shipping.partner_rules": "Règles Partenaire",
        "admin.shipping.wholesaler_rules": "Règles Grossiste",
        "admin.shipping.configure_costs": "Configurer les coûts et seuils",
        "admin.shipping.status": "Statut",
        "admin.shipping.base_cost": "Frais de Livraison de Base",
        "admin.shipping.fixed_fee_desc": "Frais fixes ajoutés aux commandes inférieures au seuil.",
        "admin.shipping.free_threshold_amount": "Livraison Gratuite (Montant)",
        "admin.shipping.amount_required_desc": "Montant requis pour la livraison gratuite.",
        "admin.shipping.free_threshold_items": "Livraison Gratuite (Articles)",
        "admin.shipping.min_items_desc": "Nombre minimum d'articles requis pour la livraison gratuite.",
        "admin.shipping.order_logic": "Logique de commande :",
        "admin.shipping.rule_logic_desc": "Les commandes coûteront {price} {currency} sauf si elles dépassent {threshold} {currency} ou contiennent au moins {items} articles.",
        "admin.shipping.rule_disabled": "La règle de livraison est actuellement désactivée.",
        "admin.shipping.no_rules": "Aucune règle de livraison trouvée. Veuillez vérifier la configuration de la base de données.",
        "admin.shipping.retry": "Réessayer le chargement",
        "admin.shipping.success_update": "Paramètres de livraison mis à jour avec succès",
        "admin.shipping.error_update": "Échec de la mise à jour des paramètres",

        // Admin Analytics
        "admin.analytics.title": "Analytique",
        "admin.analytics.subtitle": "Plongée profonde dans la performance",
        "admin.analytics.loading": "Collecte d'informations...",
        "admin.analytics.total_revenue": "Revenu Total",
        "admin.analytics.conversion_rate": "Taux de Conversion",
        "admin.analytics.active_sessions": "Sessions Actives",
        "admin.analytics.avg_order_value": "Valeur Moyenne de Commande",
        "admin.analytics.revenue_over_time": "Revenu au Fil du Temps",
        "admin.analytics.top_products": "Top Produits",
        "admin.analytics.sales_count": "{count} ventes",
        "admin.analytics.no_sales_data": "Aucune donnée de vente pour le moment",
        "admin.analytics.channel_performance": "Performance des Canaux",
        "admin.analytics.visitor_locality": "Localisation des Visiteurs",
        "admin.analytics.visitor_locality_desc": "Implémentez le suivi des sessions pour voir les données géographiques des visiteurs en temps réel.",

        // Account Managers Page
        "account_managers.title": "Gestionnaires de Compte",
        "account_managers.subtitle": "Gérer les comptes d'entreprise et les affectations de revendeurs",
        "account_managers.add_manager": "Ajouter un Gestionnaire",
        "account_managers.create_title": "Créer un Gestionnaire de Compte",
        "account_managers.create_desc": "Remplissez les détails pour créer un nouveau compte de gestionnaire dédié.",
        "account_managers.full_name": "Nom Complet",
        "account_managers.work_email": "Email Professionnel",
        "account_managers.password": "Mot de Passe",
        "account_managers.phone": "Numéro de Téléphone",
        "account_managers.create_account": "Créer le Compte",
        "account_managers.created_success": "Gestionnaire de compte créé avec succès!",
        "account_managers.no_managers": "Aucun gestionnaire trouvé",
        "account_managers.no_managers_desc": "Commencez par ajouter votre premier gestionnaire pour gérer les relations avec les revendeurs.",
        "account_managers.assigned_accounts": "Comptes Assignés",
        "account_managers.prime_goal": "Objectif Prime",
        "account_managers.edit_goal": "Modifier l'Objectif",
        "account_managers.goal_updated": "Objectif Prime mis à jour avec succès",
        "account_managers.assign_resellers": "Assigner des Revendeurs",
        "account_managers.search_resellers": "Rechercher des revendeurs...",
        "account_managers.search_managers": "Rechercher des gestionnaires par nom ou email...",
        "account_managers.no_resellers_available": "Aucun revendeur disponible pour l'assignation",
        "account_managers.assignment_updated": "Affectation mise à jour!",
        "account_managers.reseller_unassigned": "Revendeur désassigné!",
        "account_managers.delete_confirm": "Êtes-vous sûr de vouloir supprimer {name}? Cela supprimera définitivement son compte et désassignera tous ses revendeurs.",
        "account_managers.deleted_success": "Gestionnaire de compte supprimé",
        "account_managers.unassign": "Désassigner",
        "account_managers.assign": "Assigner",
        "account_managers.delete_account": "Supprimer le Compte",
        "account_managers.manage_assignments": "Gérer les Affectations",
        "account_managers.select_resellers": "Sélectionnez les revendeurs dont ce gestionnaire sera responsable.",
        "account_managers.find_reseller": "Rechercher un revendeur par entreprise ou nom de contact...",
        "account_managers.no_match_search": "Aucun revendeur disponible ne correspond à votre recherche.",
        "account_managers.all_assigned": "Tous les revendeurs sont déjà assignés à d'autres gestionnaires de compte.",
        "account_managers.reassign": "Réassigner",
        "account_managers.set_prime_goal": "Définir l'Objectif Prime",
        "account_managers.set_goal_desc": "Définissez l'objectif de revenu pour",
        "account_managers.target_revenue": "Revenu Cible (MAD)",
        "account_managers.default_revenue": "La valeur par défaut est 200 000 MAD.",
        "account_managers.update": "Mettre à Jour",
        "account_managers.save": "Enregistrer",
        "account_managers.cancel": "Annuler",
        "account_managers.manager": "Gestionnaire",
        "account_managers.active": "Actif",
        "account_managers.company": "Entreprise",
        "account_managers.contact": "Contact",
        "account_managers.email": "Email",
        "account_managers.phone_label": "Téléphone",
        "account_managers.city": "Ville",
        "account_managers.loading": "Chargement des gestionnaires de compte...",
        "account_managers.error_loading": "Échec du chargement des gestionnaires de compte",

        // Admin Resellers Page
        "admin.resellers.title": "Performance des Revendeurs",
        "admin.resellers.subtitle": "Surveillance de {count} partenaires de distribution en gros actifs",
        "admin.resellers.total_resellers": "Total Revendeurs",
        "admin.resellers.total_partners": "Total Partenaires",
        "admin.resellers.total_wholesalers": "Total Grossistes",
        "admin.resellers.partner_network": "Réseau de Partenaires",
        "admin.resellers.total_spend": "Dépenses Totales",
        "admin.resellers.all_partners": "Tous les Partenaires",
        "admin.resellers.top_spend": "Meilleures Dépenses",
        "admin.resellers.search_placeholder": "Filtrer les partenaires par nom ou entreprise...",
        "admin.resellers.loading": "Initialisation des Données Partenaires...",
        "admin.resellers.reseller_identity": "Identité du Revendeur",
        "admin.resellers.company_ice": "Entreprise / ICE",
        "admin.resellers.performance": "Performance",
        "admin.resellers.location": "Localisation",
        "admin.resellers.account_manager": "Gestionnaire de Compte",
        "admin.resellers.nexus_profile": "Profil Nexus",
        "admin.resellers.personal_account": "Compte Personnel",
        "admin.resellers.ice": "ICE",
        "admin.resellers.na": "N/A",
        "admin.resellers.unknown": "Inconnu",
        "admin.resellers.unassigned": "Non Assigné",
        "admin.resellers.view_profile": "Voir le Profil",
        "admin.resellers.no_resellers": "Aucun Partenaire Détecté",
        "admin.resellers.no_resellers_description": "Essayez d'ajuster vos filtres pour trouver des entités de distribution correspondantes.",
        "admin.resellers.reseller": "Revendeur",
        "admin.resellers.partner": "Partenaire",
        "admin.resellers.wholesaler": "Grossiste",
        "admin.resellers.total_profit": "Bénéfice Total",
        "admin.resellers.error_loading": "Échec du chargement des revendeurs",

        // Admin Customers Page
        "admin.customers.title": "Ventes Invités",
        "admin.customers.subtitle": "Surveillance de {count} clients de détail directs",
        "admin.customers.guest_database": "Base de Données Invités",
        "admin.customers.total_guest_spend": "Dépenses Total Invités",
        "admin.customers.all_guests": "Tous les Invités",
        "admin.customers.top_spend": "Meilleures Dépenses",
        "admin.customers.search_placeholder": "Rechercher des invités par nom, email, téléphone ou ID de commande...",
        "admin.customers.loading": "Initialisation des Données Invités...",
        "admin.customers.guest_user": "Utilisateur Invité",
        "admin.customers.spend": "Dépenses",
        "admin.customers.orders": "Commandes",
        "admin.customers.last_order": "Dernière Commande",
        "admin.customers.na": "N/A",
        "admin.customers.unknown": "Inconnu",
        "admin.customers.no_guests": "Aucun invité trouvé",
        "admin.customers.customer_identity": "Identité du Client",
        "admin.customers.performance": "Performance",
        "admin.customers.location": "Localisation",
        "admin.customers.actions": "Actions",
        "admin.customers.total_spent": "Total Dépensé",
        "admin.customers.total_orders": "Total Commandes",
        "admin.customers.no_guests_found": "Aucun Invité Trouvé",
        "admin.customers.no_guests_description": "Il n'y a pas encore de clients invités correspondant à vos filtres.",

        // Reseller Dashboard
        "reseller.dashboard.title": "Tableau de Bord Revendeur",
        "reseller.dashboard.welcome_back": "Bon retour, {name}",
        "reseller.dashboard.browse_catalog": "Parcourir le Catalogue",
        "reseller.dashboard.total_orders": "Total Commandes",
        "reseller.dashboard.total_value": "Valeur Totale",
        "reseller.dashboard.organization_profile": "Profil de l'Organisation",
        "reseller.dashboard.company_name": "Nom de l'Entreprise",
        "reseller.dashboard.not_set": "Non défini",
        "reseller.dashboard.business_identification": "Identification Commerciale (ICE)",
        "reseller.dashboard.location": "Localisation",
        "reseller.dashboard.site": "Site",
        "reseller.dashboard.view": "Voir",
        "reseller.dashboard.dedicated_account_manager": "Gestionnaire de Compte Dédié",
        "reseller.dashboard.no_account_manager": "Aucun gestionnaire de compte assigné pour le moment",
        "reseller.dashboard.transaction_history": "Historique des Transactions",
        "reseller.dashboard.order": "Commande",
        "reseller.dashboard.orders": "Commandes",
        "reseller.dashboard.no_transactions": "Aucune Transaction Enregistrée",
        "reseller.dashboard.initialize_trade": "Initialiser le Commerce",
        "reseller.dashboard.initialize_desc": "Commencez votre parcours de gros aujourd'hui et débloquez les prix d'inventaire de niveau 1.",
        "reseller.dashboard.start_now": "Commencer Maintenant",
        "reseller.dashboard.reference_id": "ID de Référence",
        "reseller.dashboard.timestamp": "Horodatage",
        "reseller.dashboard.fulfillment": "Exécution",
        "reseller.dashboard.volume": "Volume",
        "reseller.dashboard.action": "Action",
        "reseller.dashboard.view_order": "Voir",
        "reseller.dashboard.total": "Total",
        "reseller.dashboard.signed_out": "Déconnexion réussie",

        // Manager Dashboard
        "manager.dashboard.title": "Tableau de Bord",
        "manager.dashboard.overview": "Aperçu de vos comptes assignés",
        "manager.dashboard.assigned_clients": "Clients Assignés",
        "manager.dashboard.clients_desc": "Revendeurs, Partenaires & Grossistes",
        "manager.dashboard.total_orders": "Total Commandes",
        "manager.dashboard.total_orders_desc": "Commandes de tous les temps",
        "manager.dashboard.total_revenue": "Revenu Total",
        "manager.dashboard.total_revenue_desc": "De toutes les commandes",
        "manager.dashboard.pending_orders": "Commandes en Attente",
        "manager.dashboard.pending_orders_desc": "Nécessitent une attention",
        "manager.dashboard.recent_orders": "Commandes Récentes",
        "manager.dashboard.recent_orders_desc": "Dernières commandes de vos clients",
        "manager.dashboard.view_all": "Voir Tout",
        "manager.dashboard.no_orders": "Aucune commande pour le moment",
        "manager.dashboard.assigned_clients_title": "Clients Assignés",
        "manager.dashboard.your_reseller_accounts": "Vos comptes revendeurs",
        "manager.dashboard.no_clients": "Aucun client assigné pour le moment",

        // Manager Orders
        "manager.orders.title": "Commandes",
        "manager.orders.subtitle": "Toutes les commandes de vos clients assignés",
        "manager.orders.search_placeholder": "Rechercher des commandes...",
        "manager.orders.filter_all": "Toutes",
        "manager.orders.filter_pending": "En Attente",
        "manager.orders.filter_processing": "En Traitement",
        "manager.orders.filter_delivered": "Livrées",
        "manager.orders.filter_cancelled": "Annulées",
        "manager.orders.order_number": "N° Commande",
        "manager.orders.customer": "Client",
        "manager.orders.date": "Date",
        "manager.orders.status": "Statut",
        "manager.orders.total": "Total",
        "manager.orders.view": "Voir",
        "manager.orders.no_orders": "Aucune commande trouvée",
        "manager.orders.loading": "Chargement des commandes...",

        // Manager Resellers
        "manager.resellers.title": "Clients",
        "manager.resellers.subtitle": "Vos revendeurs, partenaires et grossistes assignés",
        "manager.resellers.search_placeholder": "Rechercher des clients...",
        "manager.resellers.revenue_goal": "Objectif de chiffre d’affaires",
        "manager.resellers.current_revenue": "Chiffre d’affaires actuel",
        "manager.resellers.target": "Cible",
        "manager.resellers.progress": "Progression",
        "manager.resellers.company": "Entreprise",
        "manager.resellers.contact": "Contact",
        "manager.resellers.email": "Email",
        "manager.resellers.phone": "Téléphone",
        "manager.resellers.city": "Ville",
        "manager.resellers.total_orders": "Total Commandes",
        "manager.resellers.total_revenue": "Revenu Total",
        "manager.resellers.view_profile": "Voir le Profil",
        "manager.resellers.no_resellers": "Aucun client trouvé",
        "manager.resellers.loading": "Chargement des clients...",
        "account_managers.assigned_partners": "Partenaires Assignés",
        "common.unknown": "Inconnu",
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("fr")

    useEffect(() => {
        // Check localStorage on mount and sanitize value
        const savedRaw = localStorage.getItem("language")
        if (savedRaw === "en" || savedRaw === "fr") {
            setLanguage(savedRaw)
        }
    }, [])

    useEffect(() => {
        localStorage.setItem("language", language)

        // Update direction on document (always LTR for French and English)
        document.documentElement.dir = "ltr"
        document.documentElement.lang = language
    }, [language])

    const t = (key: string) => {
        // Fallback defensively if language was ever something else (e.g. "ar")
        const safeLang: Language = language === "en" || language === "fr" ? language : "fr"
        const dict = translations[safeLang] as Record<string, string>
        const value = dict[key]

        if (value) return value

        // Humanized fallback instead of showing raw i18n key
        const lastSegment = key.split('.').pop() || key
        const humanized = lastSegment.replace(/_/g, ' ')
        return humanized.charAt(0).toUpperCase() + humanized.slice(1)
    }

    const toggleLanguage = () => {
        setLanguage(prev => {
            if (prev === 'fr') return 'en'
            return 'fr'
        })
    }

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            dir: "ltr",
            toggleLanguage
        }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider")
    }
    return context
}
